---
authors:
  - Ashwini Mhatre (@amhatre)
dependencies:
  ansible.netcommon: ">=5.0.0"
  ansible.utils: ">=2.9.0"
license_file: LICENSE
name: interfaces
description: Ansible Network Interfaces enables user to manage the Interfaces resources independent of platforms and perform Interfaces health checks.
namespace: network
readme: README.md
repository: https://github.com/redhat-cop/network.interfaces
issues: https://github.com/redhat-cop/network.interfaces/issues
tags: [networking]
version: 3.0.1
